backend:
  name: github
  repo: usjunco/svel
  branch: main
  base_url: https://sveltia-cms-auth.usju5296.workers.dev/
  auth_endpoint: /auth

site_url: https://www.pathogens.ibt.unam.mx
display_url: https://www.pathogens.ibt.unam.mx

media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    extension: "md"
    format: "yaml-frontmatter"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }

- name: "dashboards"
    label: "Dashboards"
    folder: "content/dashboards" # This assumes dashboards are in content/dashboards
    extension: "md"
    format: "yaml-frontmatter"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }
