backend:
  name: github
  repo: usjunco/svel # Replace this!
  base_url: https://sveltia-auth.usju5296.workers.dev
  auth_endpoint: /auth

# This is critical for local development
local_backend: true

media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts" # Adjust if your posts are in content/blog
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }
